const RIGHT 0
const DOWN 1
const LEFT 2
const UP 3
#bottomleft
ADD|IMMALL UP 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL UP 0 output
#topleft
ADD|IMMALL RIGHT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL RIGHT 0 output
#topright
ADD|IMMALL RIGHT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL DOWN 0 output
#bottomright
ADD|IMMALL DOWN 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL LEFT 0 output
ADD|IMMALL DOWN 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL UP 0 output
ADD|IMMALL RIGHT 0 output
ADD|IMMALL DOWN 0 output
